version: '3.8'

services:
  app:
    image: sinebi/authentication_app:latest
    container_name: authentication_app
    restart: always
    ports:
      - "7070:7070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://66.45.225.237:3306/mydatabase?ssl=require
      - SPRING_DATASOURCE_USERNAME=sinebi
      - SPRING_DATASOURCE_PASSWORD=PassWord@34