version: '3.8'

services:
  app:
    image: sinebi/authentication_app:latest
    container_name: authentication_app
    restart: always
    ports:
      - "7070:7070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://67.217.58.16:5432/agroconnect?ssl=require
      - SPRING_DATASOURCE_USERNAME=sinnazo
      - SPRING_DATASOURCE_PASSWORD=12345##$$