services:
  app:
    image: authentication:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.20.10.6:5432/authenticatev1
      SPRING_DATASOURCE_USERNAME: sinebi
      SPRING_DATASOURCE_PASSWORD: admin112
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
