version: '3.8'

services:
  app:
    image: sinebi/authentication_app:latest
    container_name: authentication_app
    restart: always
    ports:
      - "7070:7070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:26654/{DB_NAME}?ssl=require
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}



#services:
#  app:
#    image: authentication:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "7070:7070"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://67.217.58.16:5432/authenticatev1
#      SPRING_DATASOURCE_USERNAME: sinebi
#      SPRING_DATASOURCE_PASSWORD: 12345##@@
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
