version: '3.8'

services:
  app:
    image: sinebi/authentication_app:latest
    container_name: authentication_app
    restart: always
    ports:
      - "7070:7070"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_CREDENTIALS_USR}
      - SPRING_DATASOURCE_PASSWORD=${DB_CREDENTIALS_PSW}
